CREATE TABLE PUBLIC.SAMPLE (
   key           INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY
  ,index         INTEGER
  ,guid          VARCHAR(36)
  ,isActive      VARCHAR(1)
  ,balance       NUMERIC(6,2)
  ,picture       VARCHAR(1024)
  ,age           INTEGER 
  ,eyeColor      VARCHAR(5)
  ,name          VARCHAR(512)
  ,gender        VARCHAR(6)
  ,company       VARCHAR(256)
  ,email         VARCHAR(256)
  ,phone         VARCHAR(18)
  ,address       VARCHAR(512)
  ,about         VARCHAR(1024)
  ,registered    DATE 
  ,latitude      NUMERIC(8,6)
  ,longitude     NUMERIC(9,6)
  ,greeting      VARCHAR(1024)
  ,favoriteFruit VARCHAR(64)
);

CREATE TABLE PUBLIC.SAMPLE_CODE (
   code         VARCHAR(16)
  ,key			VARCHAR(16)
  ,val			VARCHAR(16)
);
CREATE UNIQUE INDEX PUBLIC.IDX_SAMPLE_CODE ON PUBLIC.SAMPLE_CODE (code, key)